default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 2240

development:
  <<: *default
  database: blogapp_development

test:
  <<: *default
  database: blogapp_test

production:
  <<: *default
  database: blogapp_production
  username: blogapp
  password: <%= ENV["BLOGAPP_DATABASE_PASSWORD"] %>
